name: Package Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Gitleaks Job
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2.3.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  # Code Formatting and Linting Job
  formatting-and-linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # OS matrix
        python-version: ["3.10", "3.11"]  # Python version matrix
    needs: gitleaks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # Run ruff for code formatting and linting
      - name: Run ruff
        run: ruff check --config 'pyproject.toml' .

  # Dependency Check Job with Pip Audit
  dependency-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # OS matrix
        python-version: ["3.10", "3.11"]  # Python version matrix
    needs: formatting-and-linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit  

      - name: Run pip-audit
        run: |
          pip-audit || true